Znode80_Dev/Znode.Engine.MvcAdminNew/Models/ListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Znode.Engine.MvcAdmin.Models
{
    public class ListViewModel
    {
        public int[] AssignedId { get; set; }
        public int[] UnAssignedId { get; set; }
        public IEnumerable<SelectListItem> AssignedList { get; set; }
        public IEnumerable<SelectListItem> UnAssignedList { get; set; }
    }
}

Znode80_Dev/Znode.Engine.MvcAdminNew/Models/ManageViewModels.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;

namespace Znode.Engine.MvcAdmin.Models
{
    public class IndexViewModel
    {
        public bool HasPassword { get; set; }
        public IList<UserLoginInfo> Logins { get; set; }
        public string PhoneNumber { get; set; }
        public bool TwoFactor { get; set; }
        public bool BrowserRemembered { get; set; }
    }

    public class ManageLoginsViewModel
    {
        public IList<UserLoginInfo> CurrentLogins { get; set; }
        public IList<AuthenticationDescription> OtherLogins { get; set; }
    }

    public class FactorViewModel
    {
        public string Purpose { get; set; }
    }

    public class SetPasswordViewModel
    {
        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class ChangePasswordViewModel
    {
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Current password")]
        public string OldPassword { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class AddPhoneNumberViewModel
    {
        [Required]
        [Phone]
        [Display(Name = "Phone Number")]
        public string Number { get; set; }
    }

    public class VerifyPhoneNumberViewModel
    {
        [Required]
        [Display(Name = "Code")]
        public string Code { get; set; }

        [Required]
        [Phone]
        [Display(Name = "Phone Number")]
        public string PhoneNumber { get; set; }
    }

    public class ConfigureTwoFactorViewModel
    {
        public string SelectedProvider { get; set; }
        public ICollection<System.Web.Mvc.SelectListItem> Providers { get; set; }
    }
}

Znode80_Dev/Znode.Engine.MvcAdminNew/Controllers/Setup/StoresController.cs
using Resources;
using System.Web.Mvc;
using Znode.Engine.Api.Client.Filters;
using Znode.Engine.MvcAdmin.Agents;
using Znode.Engine.MvcAdmin.Helpers;
using Znode.Engine.MvcAdmin.Models;
using Znode.Engine.MvcAdmin.ViewModels;

namespace Znode.Engine.MvcAdmin.Controllers
{
    /// <summary>
    /// Store Controller
    /// </summary>
    public class StoresController : BaseController
    {
        #region Private Variables
        private readonly IPortalAgent _portalAgent;
        private readonly IDomainAgent _domainAgent;
        private const string ManageView = "Manage";
        private const string AddUrlView = "CreateEditUrl";
        private const string ListView = "List";
        #endregion

        #region Constructor
        /// <summary>
        /// Constructor for Stores Controller.
        /// </summary>
        public StoresController()
        {
            _portalAgent = new PortalAgent();
            _domainAgent = new DomainAgent();
        }
        #endregion

        #region Public Methods

        /// <summary>
        /// Deletes the specified portal
        /// </summary>
        /// <param name="portalId">Portal id</param>
        /// <returns>Redirects to list view with deleted portal.</returns>
        
        public JsonResult Delete(int id)
        {
            bool status = false;
            string message = string.Empty;
            bool isFadeOut = CheckIsFadeOut();

            if (!id.Equals(0))
            {
                status = _portalAgent.DeletePortal(id);
              message = status ? ZnodeResources.DeleteMessage : ZnodeResources.ErrorStoreDelete;
            }           
            return Json(new { sucess = status, message = message, id = id, isFadeOut = isFadeOut });
        }

        /// <summary>
        /// Gets the main page of the store.
        /// </summary>
        /// <returns>View of the store's main page.</returns>
        public ActionResult List([ModelBinder(typeof(PageDataBinder))] FilterCollectionDataModel model)
        {
            PortalListViewModel portals = _portalAgent.GetPortals(model.Filters, model.SortCollection, model.Page, model.RecordPerPage);
            return ActionView(portals);
        }

        /// <summary>
        /// To show Manage View in Tabs
        /// </summary>
        /// <param name="id">Portal Id</param>
        /// <returns></returns>
        public ActionResult Manage(int id = 0)
        {
            TempData["PortalId"] = id;
            DomainListViewModel model = new DomainListViewModel();
            model = _domainAgent.GetDomains(id);
            return View(ManageView, model);
        }

        /// <summary>
        /// To Show Add/Edit Domain Url View.
        /// </summary>
        /// <param name="id">Portal Id</param>
        /// <returns></returns>
        public ActionResult AddUrl(int id = 0)
        {
            DomainViewModel model = new DomainViewModel();
            model.PortalId = id;
            return View(AddUrlView, model);
        }

        /// <summary>
        /// Add Domain url
        /// </summary>
        /// <param name="Model">DomainViewModel</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult AddUrl(DomainViewModel Model)
        {
            TempData[MvcAdminConstants.Notifications] = _domainAgent.createDomainUrl(Model) 
                ? GenerateNotificationMessages(ZnodeResources.SaveMessage, NotificationType.success) 
                : GenerateNotificationMessages(ZnodeResources.SaveErrorMessage, NotificationType.error);
            return RedirectToAction(ManageView, new { @id = Model.PortalId });
        }

        /// <summary>
        /// To show Add/edit Domain url view. 
        /// </summary>
        /// <param name="id">int Portal id</param>
        /// <param name="domainId">int domain id</param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Edit(int? id, int domainId)
        {
            if (!Equals(id, null))
            {
                DomainViewModel viewModel = _domainAgent.GetDomain(domainId);
                if (Equals(viewModel, null))
                {
                    return RedirectToAction(AddUrlView, new { @id = id });
                }
                return View(AddUrlView, viewModel);
            }
            return View(AddUrlView);
        }

        /// <summary>
        /// To update Domain Url data
        /// </summary>
        /// <param name="model">ProductTypesViewModel model</param>
        /// <returns>show susscess/fail message and redirect to list page</returns>
        [HttpPost]
        public ActionResult Edit(DomainViewModel ViewModel)
        {
            if (ModelState.IsValid)
        {
                TempData[MvcAdminConstants.Notifications] = _domainAgent.UpdateDomainUrl(ViewModel) 
                    ? GenerateNotificationMessages(ZnodeResources.UpdateMessage, NotificationType.success) 
                    : GenerateNotificationMessages(ZnodeResources.UpdateErrorMessage, NotificationType.error);
                return RedirectToAction(ManageView, new { @id = ViewModel.PortalId });
            }
            return View(ViewModel);
        }

        /// <summary>
        /// Gets Create a store page for creating a store.
        /// </summary>
        /// <returns>View for creating store.</returns>
        [HttpGet]
        public ActionResult Create()
        {
            PortalViewModel portalViewModel = new PortalViewModel();
            portalViewModel=_portalAgent.BindPortalInformation(portalViewModel);
            return View(portalViewModel);
        }

        /// <summary>
        /// Creates a portal
        /// </summary>
        /// <param name="portalViewModel"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Create(PortalViewModel portalViewModel)
        {
            string notification = string.Empty;
            portalViewModel.LogoPathImageName = portalViewModel.LogoPath.FileName;
            bool isPortalCreated = _portalAgent.CreatePortal(portalViewModel, out notification);

            if(isPortalCreated)
            {
                //To be redirected to manage page's first tab of Stores
               
            }
            portalViewModel = _portalAgent.BindPortalInformation(portalViewModel);
            TempData["ErrorMessage"] = notification;
            return View(portalViewModel);
        }

        /// <summary>
        /// Deletes an existing Domain Url.
        /// </summary>
        /// <param name="id">domain Id</param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult DeleteDomain(int? id)
        {
            bool status = false;
            string message = string.Empty;
            bool isFadeOut = CheckIsFadeOut();
            if (!Equals(id, null))
            {
                status = _domainAgent.DeleteDomainUrl(id.Value);
                message = status ? ZnodeResources.DeleteMessage : ZnodeResources.ErrorDeleteProductType;
            }
            return Json(new { sucess = status, message = message, id = id, isFadeOut = isFadeOut });
        }
        /// <summary>
        /// Copies a store.
        /// </summary>
        /// <param name="portalId"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Copy(int portalId)
        {
            bool isPortalCopied = _portalAgent.CopyStore(portalId);
            if (!isPortalCopied)
            {
                TempData["ErrorMessage"] = ZnodeResources.ErrorCopyStore;
            }
            return RedirectToAction("List");
        }
        #endregion

        /// <summary>
        /// Gets Css list according to Theme id.
        /// </summary>
        /// <param name="CssThemeId"></param>
        /// <returns></returns>
        [HttpGet]
        public JsonResult BindCssList(int CssThemeId)
        {
            CategoryNodeViewModel model = new CategoryNodeViewModel();
            FilterCollection filters = new FilterCollection();
            filters.Add(new FilterTuple(FilterKeys.CSSThemeId, FilterOperators.Equals, CssThemeId.ToString()));
            var list = _portalAgent.BindCssList(filters);
            return Json(list, JsonRequestBehavior.AllowGet);
        }

    }
}

Znode80_Dev/Znode.Engine.MvcAdminNew/Views/Stores/Create.cshtml
@model Znode.Engine.MvcAdmin.ViewModels.PortalViewModel

@{
    ViewBag.Title = "Create a Store";
}

<h2>Create a Store</h2>

@using (Html.BeginForm("Create", "Stores", FormMethod.Post, new { @class = "form", enctype = "multipart/form-data" }))
{
    <div class="col-sm-12 dashboard-page-container">
        <h4>Store Identity</h4>
        <hr />
        <div class="form-group">
            @Html.LabelFor(m => m.CompanyName)
            @Html.TextBoxFor(m => m.CompanyName)
            @Html.ValidationMessageFor(m => m.CompanyName)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.StoreName)
            @Html.TextBoxFor(m => m.StoreName)
            @Html.ValidationMessageFor(m => m.StoreName)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.CatalogId)
            @Html.DropDownListFor(m => m.CatalogId, Model.Catalogs, new { @id = "ddlCatalog" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.ThemeId)
            @Html.DropDownListFor(m => m.ThemeId, Model.Themes, new { @id = "ddlTheme", @onchange = "Portal.BindCssList(ddlCSS,this)" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.CSSId)
            @Html.DropDownListFor(m => m.CSSId, Model.CSS, new { @id = "ddlCSS" })
        </div>
        <div class="form-group hidden">
            @Html.LabelFor(m => m.LocaleId)
            @Html.DropDownListFor(m => m.LocaleId, Model.Locales, new { @id = "ddlLocale" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.LogoPath)
            @Html.EditorFor(m => m.LogoPath)
        </div>
        <h4>Security</h4>
        <hr />
        <div class="form-group">
            <label>
                @Html.LabelFor(m => m.UseSsl)
                <input type="checkbox" id="@Model.UseSsl" name="@Model.UseSsl" value="@Model.UseSsl" />
                <span class="lbl padding-8"></span>
            </label>
        </div>
        <h4>Store Contact Information</h4>
        <hr />
        <div class="form-group">
            @Html.LabelFor(m => m.AdminEmail)
            @Html.TextBoxFor(m => m.AdminEmail)
            @Html.ValidationMessageFor(m => m.AdminEmail)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.SalesEmail)
            @Html.TextBoxFor(m => m.SalesEmail)
            @Html.ValidationMessageFor(m => m.SalesEmail)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.CustomerServiceEmail)
            @Html.TextBoxFor(m => m.CustomerServiceEmail)
            @Html.ValidationMessageFor(m => m.CustomerServiceEmail)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.SalesPhoneNumber)
            @Html.TextBoxFor(m => m.SalesPhoneNumber)
            @Html.ValidationMessageFor(m => m.SalesPhoneNumber)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.CustomerServicePhoneNumber)
            @Html.TextBoxFor(m => m.CustomerServicePhoneNumber)
            @Html.ValidationMessageFor(m => m.CustomerServicePhoneNumber)
        </div>
        <h4>Default Settings</h4>
        <hr />
        <div class="form-group">
            @Html.LabelFor(m => m.DefaultReviewStatus)
            @Html.DropDownListFor(m => m.DefaultReviewStatus, Model.DefaultReviewStates, new { @id = "ddlDefaultReviewStatus" })
        </div>
        <div>
            @Html.LabelFor(m => m.DefaultOrderStateId)
            @Html.DropDownListFor(m => m.DefaultOrderStateId, Model.OrderState, new { @id = "ddlOrderState" })
        </div>
        <div>
            <label>
                @Html.LabelFor(m => m.PersistentCartEnabled)
                <input type="checkbox" id="@Model.PersistentCartEnabled" name="@Model.PersistentCartEnabled" value="@Model.PersistentCartEnabled" />
                <span class="lbl padding-8"></span>
            </label>
        </div>
        <div>
            <label>
                @Html.LabelFor(m => m.EnableAddressValidation)
                <input type="checkbox" id="@Model.EnableAddressValidation" name="@Model.EnableAddressValidation" value="@Model.EnableAddressValidation" />
                <span class="lbl padding-8"></span>
            </label>
        </div>
        <div>
            <label>
                @Html.LabelFor(m => m.RequireValidatedAddress)
                <input type="checkbox" id="@Model.RequireValidatedAddress" name="@Model.RequireValidatedAddress" value="@Model.RequireValidatedAddress" />
                <span class="lbl padding-8"></span>
            </label>
        </div>
        <div>
            <label>
                @Html.LabelFor(m => m.EnableCustomerPricing)
                <input type="checkbox" id="@Model.EnableCustomerPricing" name="@Model.EnableCustomerPricing" value="@Model.EnableCustomerPricing" />
                <span class="lbl padding-8"></span>
            </label>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.DefaultProductReviewStateId)
            @Html.DropDownListFor(m => m.DefaultProductReviewStateId, Model.ProductReviewState, new { @id = "ddlProductReviewState" })
        </div>
        <div class="form-group">
            <button type="submit" class="btn-text red">Submit</button>
            <button type="button" class="btn-text grey">Cancel</button>
        </div>
    </div>


    @Scripts.Render("~/bundles/portal")

    <script>
        $j(document).ready(function () {
            Portal.BindCssList(ddlCSS, ddlTheme);
        })
    </script>

}

Znode80_Dev/Znode.Engine.MvcAdminNew/Views/Stores/CreateEditUrl.cshtml
@model Znode.Engine.MvcAdmin.ViewModels.DomainViewModel
@{
    ViewBag.Title = "AddUrl";
    string actionName = ViewContext.Controller.ValueProvider.GetValue("action").RawValue.ToString();
    string controllerName = ViewContext.RouteData.Values["controller"].ToString();
}

@using (Html.BeginForm(actionName, controllerName, FormMethod.Post))
{
    string isActiveStatus = "checked='checked'";
    if (Model.DomainName != null)
    {
        isActiveStatus = (!Equals(Model, null) && Model.IsActive) ? "checked='checked'" : string.Empty;
    }
    
    @Html.ValidationSummary(true)
    @Html.HiddenFor(moel => Model.PortalId)
    @Html.HiddenFor(moel => Model.DomainId)
    
    <div class="col-sm-12 dashboard-page-container">
        <div class="col-sm-12 title-container">
            <h1>@ZnodeResources.HeaderAddNewURL</h1>
        </div>
        <div class="col-sm-5 add-new-container">
            @Html.ValidationSummary(true)
            <div class="form-group">
                <div class="col-sm-4 nopadding">
                    @Html.LabelFor(model => model.DomainName)
                    <p class="sub">Enter a fully qualified URL (example: http://mysite.com). Note that the "www" and any port number will be ignored.</p>
                </div>
                <div class="col-sm-8">
                    @Html.TextBoxFor(m => m.DomainName, new { @placeholder = @ZnodeResources.PlaceHolderDomainName })
                    @Html.ValidationMessageFor(m => m.DomainName)
                </div>                
            </div>
            <div class="form-group">
                <div class="col-sm-12 nopadding">
                    <label>
                        <input @isActiveStatus id="IsActive" name="IsActive" type="checkbox" value="true">
                        <span class="lbl padding-8">@ZnodeResources.LabelEnableUrl</span>
                        <input name="IsActive" type="hidden" value="false">
                    </label>
                </div>                
            </div>
            <div class="pull-right">
                <button type="submit" class="btn-text red" title="@ZnodeResources.ButtonSubmitRequest">@ZnodeResources.ButtonSubmitRequest</button>
                <button type="button" class="btn-text grey" title="@ZnodeResources.ButtonCancel" onclick="javascript: location.href = '/Stores/List';">@ZnodeResources.ButtonCancel</button>        
            </div>
        </div>
    </div>
    
}

Znode80_Dev/Znode.Engine.MvcAdminNew/Views/Stores/List.cshtml
@model Znode.Engine.MvcAdmin.ViewModels.PortalListViewModel

<div id="grid-container">    
    <div class="col-sm-12 dashboard-page-container">

        @if (!Equals(@TempData["Notification"], null))
        {
            <div class='MessageBox alert alert-info'><p>@TempData["Notification"]</p></div>
        }
        @if (!Equals(@TempData["ErrorMessage"], null))
        {
            <div class='MessageBox alert alert-danger'><p>@TempData["Notification"]</p></div>
        }
      
        <div class="col-sm-12 title-container">
            <h1 class="left">
                @ZnodeResources.ManageStoresHeading
                <a data-toggle="popover" data-contentwrapper=".popover-content"><i class="glyphicon glyphicon-question-sign" data-toggle="tooltip" data-placement="top" data-original-title="Click Here"></i> </a>                            
            </h1>
            <p class="left">@ZnodeResources.StorefrontDescription</p>
        </div>
        <div class="col-sm-12 search-container">
            <div class="col-lg-6 col-md-8 col-sm-8 nopadding">
                @using (Ajax.BeginForm("List", "Stores", new AjaxOptions() { UpdateTargetId = "grid-container", OnSuccess = "WebgridHelper.GridUpdateHandler" }, new { @id = "searchform" }))
                {
                    <div class="col-sm-5 nopadding">
                        @Html.TextBoxFor(m => m.SearchStore, new { @placeholder = ZnodeResources.SearchStoresHeader, @Name = "storename" })
                    </div>
                    <div class="col-sm-7 ClearBoth">
                        <button type="submit" name="Search" id="btnSearch" class="btn-text red" title="@ZnodeResources.ButtonSearch">@ZnodeResources.ButtonSearch</button>
                        <button type="reset" class="btn-text grey" title="@ZnodeResources.ButtonClear">@ZnodeResources.ButtonClear</button>                    
                        @*@Html.ActionLink("Clear", "List")*@
                    </div>
                }

            </div>
            <div class="col-lg-6 col-md-4 col-sm-4 nopadding">
                <button type="button" onclick="javascript: location.href = '/Stores/Create';" class="btn-text red pull-right" title="@ZnodeResources.ButtonAddNewStore">@ZnodeResources.ButtonAddNewStore</button>                
            </div>
        </div>
        <div class="col-sm-12 list-container">
            <h3>@ZnodeResources.StoreListHeader</h3>
            @Html.Partial("_List", Model)
        </div>

    </div>
</div>
<div class="popover-content hide">
    <h3>Help</h3>
    <p>You can create a new storefront or manage an existing one. To create a new storefront follow these steps:</p>
    <p>(1) Click the "Add New Store" button</p>
    <p>(2) Add one or more URLs to the store</p>
    <p>(3) Add at least one profile to use as the default anonymous profile</p>
    <p>(4) Add at least one profile to use as the default registered profile</p>
    <p>(5) Configure other store settings including SMTP, Currencies, Shipping and Analytics </p>
</div>

@*Script For PopOver Contain*@
<script>
    $(function () {
        $('[data-toggle="popover"]').popover({
            html: true,
            placement: 'bottom',
            content: function () {
                return $($(this).data('contentwrapper')).html();
            }
        });
    })
</script>

Znode80_Dev/Znode.Engine.MvcAdminNew/Views/Stores/_List.cshtml
@model Znode.Engine.MvcAdmin.ViewModels.PortalListViewModel
@using Resources;

@{
    string controllerName = ViewContext.RouteData.Values["controller"].ToString();
}

@if (!Equals(Model, null) && Model.Portals.Count > 0)
{
    <div>
        @{

    WebGrid grid = new WebGrid(rowsPerPage: Model.RecordPerPage, ajaxUpdateContainerId: "grid-container");
    grid.Bind(source: Model.Portals, rowCount: Model.TotalResults, autoSortAndPage: false);

}
        <div id="grid">
    @grid.GetHtml(
         htmlAttributes: new { id = "grid", @class = "table" },
         headerStyle: "grid-header",
         columns: new[] {
            grid.Column(columnName: "PortalID", header: "ID"),
            grid.Column(header: @ZnodeResources.TitleStoreName, format: @<span> <span id="spanName_@item.StoreName">@item.StoreName</span></span>),
            grid.Column(header: @ZnodeResources.TitleBrandName, format: @<span> <span id="spanName_@item.CompanyName">@item.CompanyName</span></span>),
            grid.Column(header: @ZnodeResources.LabelAction, format: @<text> @Html.Raw(string.IsNullOrEmpty(item.DomainName) ? "<a href='#' id='Preview_@item.PortalID' class='edit'>" + @ZnodeResources.PreviewText + "</a>" : "<a href='http://" + @item.DomainName + "' id='Preview_@item.PortalID' target='_blank'>" + @ZnodeResources.PreviewText + "</a>")</text>),
            grid.Column(header: "",format:@<text>@Html.ActionLink(@ZnodeResources.ManageText, "Manage", new { @id = @item.PortalId })</text>),
                grid.Column(header: "",format:@<text> <a href="/Stores/Copy?portalId=@item.PortalID" id="Copy_@item.PortalID" style="display:block" class="copy">@ZnodeResources.CopyText</a></text>),
                grid.Column(header: "",format:@<text>@Html.Raw(!item.IsCurrentPortal?"<span class='delete-link' onclick='CommonHelper.BindDeleteConfirmDialog(\" " + ZnodeResources.ConfirmDeleteTitle + "\", \" " + ZnodeResources.ConfirmDeleteMessage + "\", \"/" + controllerName + "/" + ZnodeResources.LabelDelete + "/" + @item.PortalID + "\");'>" + ZnodeResources.LabelDelete + "</span>":"")</text>)
        }
    )
    @grid.CustomPager(Html)
    @Html.Hidden("dir", grid.SortDirection) @Html.Hidden("col", grid.SortColumn)
</div>
    </div>
}
else
{
    <div>@ZnodeResources.NoRecordFoundMessageText</div>
}

Znode80_Dev/Znode.Engine.MvcAdminNew/Views/Stores/_Url.cshtml
@model Znode.Engine.MvcAdmin.ViewModels.DomainListViewModel
@using Resources;
@{
    string controllerName = ViewContext.RouteData.Values["controller"].ToString();
}
<div class="col-sm-12">
    <div class="pull-right top-btn">
        <button type="button" class="btn-text red" onclick="javascript: location.href = '/Stores/AddUrl/'+@TempData["PortalId"];"> Add URL </button>
        <button type="button" class="btn-text grey" onclick="javascript: location.href = '/Stores/List/';">Cancel</button>
    </div>
</div>
<div class="col-sm-12">
    @if (!Equals(Model, null) && Model.Domains.Count > 0)
    {

        WebGrid grid = new WebGrid(rowsPerPage: 5, ajaxUpdateContainerId: "grid-container");
        grid.Bind(source: Model.Domains, rowCount: 5, autoSortAndPage: false);


        <div>
            @grid.GetHtml(
         htmlAttributes: new { id = "grid", @class = "table" },
         fillEmptyRows: false,
            mode: WebGridPagerModes.All,
            firstText: "<< First",
            previousText: "< Prev",
            nextText: "Next >",
            lastText: "Last >>",
            columns: new[] {
grid.Column(header: @ZnodeResources.TitleId,format: @<span> <span id="spanName_@item.DomainID">@item.DomainID</span></span>),
grid.Column(header: @ZnodeResources.TitleDomainName, format: @<span> <span id="spanName_@item.DomainName">@item.DomainName</span></span>),
grid.Column(header: @ZnodeResources.TitleUrlKey, format: @<span> <span id="spanName_@item.ApiKey">@item.ApiKey</span></span>),
grid.Column(header: @ZnodeResources.TitleIsActive, format: @<span> <span id="spanName_@item.IsActive">@item.IsActive</span></span>),
         grid.Column(header: @ZnodeResources.LabelAction,format:@<text> @Html.ActionLink(ZnodeResources.LabelEdit, ZnodeResources.LabelEdit, new { @id = @item.PortalID, @domainId = @item.DomainID }, new { @title = @ZnodeResources.LabelEdit })  </text>),
         grid.Column(header: "",format:@<text>@Html.Raw("<span class='delete-link' title='Delete' onclick='CommonHelper.BindDeleteConfirmDialog(\" " + ZnodeResources.ConfirmDeleteTitle + "\", \" " + ZnodeResources.ConfirmDeleteMessage + "\", \"/" + "Stores" + "/" + ZnodeResources.LabelDeleteDomain + "/" + @item.DomainID + "\");'>" + ZnodeResources.LabelDelete + "</span>")</text>)}
          )
            @grid.CustomPager(Html)
            @Html.Hidden("dir", grid.SortDirection) @Html.Hidden("col", grid.SortColumn)
        </div>

    }
    else
    {
        <div>@ZnodeResources.NoRecordFoundMessageText</div>
    }
</div>